name: CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.12'

    - name: Install Jupyter
      run: |
        python -m pip install --upgrade pip
        pip install jupyter

    - name: Run User A's notebook
      run: |
        jupyter nbconvert --to notebook --execute userA_example_program.ipynb --inplace || exit 1

    - name: Run User B's notebook
      run: |
        jupyter nbconvert --to notebook --execute userB_example_program.ipynb --inplace || exit 1
