name: Enhanced CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run User A's script
      run: python userA_example_program.py
      
    - name: Run User B's script
      run: python userB_example_program.py

    - name: Run tests
      id: run_tests
      run: |
        pytest test_example.py > result.log; echo $? > result.txt
        if [ "$(cat result.txt)" -ne 0 ]; then
          echo "failed" >> result.txt
        else
          echo "passed" >> result.txt
        fi
      continue-on-error: true

    - name: Send notification
      run: |
        RESULT=$(cat result.txt)
        curl -X POST -H "Content-Type: application/json" -d "{\"status\":\"$RESULT\"}" YOUR_WEBHOOK_URL
